export const projects = [
    { 
        image: '/rateeat.jpg',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/rateeatDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/protol.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/labconnect.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
    { 
        image: '/booking.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2021',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 mb-5 h-64 gap-x-4',
    },
]